/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana_Login;

import javax.swing.JOptionPane;

/**
 *
 * @author MARTHA
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        EtiquetaLabel = new javax.swing.JLabel();
        EtiquetaUsuario = new javax.swing.JLabel();
        EtiquetaContraseña = new javax.swing.JLabel();
        CajaUsuario = new javax.swing.JTextField();
        CajaContraseña = new javax.swing.JPasswordField();
        BotonSesion = new javax.swing.JButton();
        ImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 80, 40));

        EtiquetaLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\Login\\src\\main\\java\\Imagenes\\Login.png")); // NOI18N
        jPanel1.add(EtiquetaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 320, 360));

        EtiquetaUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EtiquetaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaUsuario.setText("Usuario:");
        jPanel1.add(EtiquetaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 110, 40));

        EtiquetaContraseña.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EtiquetaContraseña.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaContraseña.setText("Contraseña:");
        jPanel1.add(EtiquetaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, -1, -1));

        CajaUsuario.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(CajaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 230, 30));

        CajaContraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(CajaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 230, 30));

        BotonSesion.setBackground(new java.awt.Color(153, 153, 153));
        BotonSesion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonSesion.setText("Iniciar Sesion");
        BotonSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSesionActionPerformed(evt);
            }
        });
        jPanel1.add(BotonSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, -1, -1));

        ImagenFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\Login\\src\\main\\java\\Imagenes\\Fondo.jpg")); // NOI18N
        jPanel1.add(ImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BotonSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSesionActionPerformed
        // TODO add your handling code here:
        
        String usuarioCorrecto = "carlos";
        String contraseñaCorrecta = "carlos123";
        
        if(usuarioCorrecto.equals(CajaUsuario.getText())){
            String contraseña = "";
            
            for(int i=0;i<CajaContraseña.getPassword().length;i++){
                
                contraseña+=CajaContraseña.getPassword()[i];
                
            }
            
            if(contraseñaCorrecta.equals(contraseña)){
                JOptionPane.showMessageDialog(null, "Ingresaste al sistema");
            }else{
                
                JOptionPane.showMessageDialog(null, "Contraseña Incorrecta");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Error, Usuario desconocido");
        }
        
    }//GEN-LAST:event_BotonSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            System.out.println("ClassNotFoundException");
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            System.out.println("InstantiationException");
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            System.out.println("IllegalAccessException");
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            System.out.println("UnsupportedLookAndFeelException");
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSesion;
    private javax.swing.JPasswordField CajaContraseña;
    private javax.swing.JTextField CajaUsuario;
    private javax.swing.JLabel EtiquetaContraseña;
    private javax.swing.JLabel EtiquetaLabel;
    private javax.swing.JLabel EtiquetaUsuario;
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
